[profile.default]
solc = '0.8.23'
evm_version = 'paris'
via_ir = true
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
optimizer = true
optimizer_runs = 10_000_000
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'account-abstraction/=lib/account-abstraction/contracts/',
]

# 添加预编译合约配置
precompiles = [
    "0x06=bls12_381_g1_add",
    "0x07=bls12_381_g1_mul", 
    "0x08=bls12_381_pairing"
]

[fuzz]
runs = 5000

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
goerli = "${RPC_URL_GOERLI}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
ignore = ['src/external/**/*']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
